services:
  - type: web
    name: dojdu-cms
    env: node
    rootDir: cms
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      # Generate strong secrets in the Render dashboard after creating the service
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
    disk:
      name: strapi-data
      mountPath: /opt/render/project/src/.tmp
      sizeGB: 1

